# Generated by Django 4.1.3 on 2023-02-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_staduim_event_stadium_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
